"""
Attesta — the audit report (what the client actually pays for).

Turns a tamper-evident ledger into a human-readable "AI Agent Activity Report":
what the agent did, what was blocked, who approved what, and — crucially — a
verified integrity verdict from the Attesta core.
"""
from .ledger import Ledger
from .verifier import verify


def audit_report(ledger_path, key=None, client="[client]", agent="[agent]", period="[period]"):
    led = Ledger.load(ledger_path)
    v = verify(ledger_path, key=key)

    sends = [e for e in led.entries if e["type"] == "gateway" and e["name"] == "sent"]
    blocked = [e for e in led.entries if e["type"] == "gateway" and e["name"] == "blocked"]
    approvals = [e for e in led.entries if e["type"] == "approval"]
    checks = [e for e in led.entries if e["type"] == "policy"]

    L = []
    L.append("# AI Agent Activity Report")
    L.append("")
    L.append(f"- **Client:** {client}")
    L.append(f"- **Agent:** {agent}")
    L.append(f"- **Period:** {period}")
    L.append(f"- **Total recorded actions:** {len(led.entries)}")
    L.append("")
    L.append("## Integrity (Attesta core)")
    L.append(f"- Tamper-evident chain: **{'INTACT ✓' if v['intact'] else 'FAILED ✗'}**")
    L.append(f"- Merkle root: `{v['merkle_root'][:32]}...`")
    if "signature_valid" in v:
        L.append(f"- Seal signature: {'valid' if v['signature_valid'] else 'INVALID'}")
    L.append("")
    L.append("## Summary")
    L.append(f"- Messages sent (after approval): **{len(sends)}**")
    L.append(f"- Risky messages blocked by policy: **{len(blocked)}**")
    L.append(f"- Human approvals/edits: **{len(approvals)}**")
    L.append(f"- Policy checks run: **{len(checks)}**")
    L.append("")
    L.append("## Timeline")
    for e in led.entries:
        p = e.get("payload", {})
        detail = _summarize(e["type"], e["name"], p)
        L.append(f"- `#{e['seq']:>2}` **{e['type']}:{e['name']}** — {detail}")
    L.append("")
    L.append("*Evidence generated by Attesta. Every line above is committed to a hash-chained,"
             " tamper-evident ledger — edit any entry and the chain breaks visibly on re-verification.*")
    return "\n".join(L)


def _summarize(etype, name, p):
    if etype == "policy":
        rs = ", ".join(r["reason"] for r in p.get("reasons", [])) or "—"
        return f"decision={p.get('decision')} ({rs})"
    if etype == "gateway" and name == "blocked":
        return "BLOCKED: " + ", ".join(r["reason"] for r in p.get("reasons", []))
    if etype == "gateway" and name == "sent":
        return f"sent on {p.get('channel')} (approved_by={p.get('approved_by')})"
    if etype == "approval":
        return f"{name} by {p.get('by')}" + (" (edited)" if p.get("edited") else "")
    if etype == "tool":
        return f"executed {name}"
    if etype == "llm":
        return f"drafted ({name})"
    if etype == "time":
        return "timestamp"
    return name


def audit_csv(ledger_path):
    led = Ledger.load(ledger_path)
    rows = ["seq,type,name,entry_hash"]
    for e in led.entries:
        rows.append(f"{e['seq']},{e['type']},{e['name']},{e.get('entry_hash', '')[:16]}")
    return "\n".join(rows)
